# Generated by Django 4.2.3 on 2023-07-24 07:16

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=100)),
                ('eposta', models.CharField(max_length=30)),
                ('sifre', models.CharField(max_length=128)),
                ('telefon', models.CharField(max_length=50, null=True)),
                ('adres', models.CharField(max_length=300, null=True)),
                ('yas', models.CharField(max_length=5, null=True)),
                ('il', models.CharField(max_length=20, null=True)),
                ('isi', models.CharField(max_length=30, null=True)),
                ('hak', models.CharField(max_length=200, null=True)),
                ('resim', models.ImageField(null=True, upload_to=pages.models.resim)),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('telefon', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ogrenciler', models.ManyToManyField(to='pages.ogrenci')),
            ],
        ),
    ]
