# Generated by Django 4.2.3 on 2023-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogrenci',
            name='telefon',
            field=models.IntegerField(null=True),
        ),
    ]
