# Generated by Django 4.2.3 on 2023-07-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sepet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
                ('resim', models.CharField(max_length=1000)),
                ('adet', models.IntegerField()),
                ('toplam', models.IntegerField()),
                ('onay', models.IntegerField()),
            ],
        ),
    ]
