# Generated by Django 4.2.3 on 2023-07-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sepet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sepet',
            name='alan',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
