# Generated by Django 4.2.3 on 2023-07-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_kullanici_adres_kullanici_il_kullanici_telefon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='isi',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
