# Generated by Django 4.2.3 on 2023-07-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ogrenci_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=30)),
                ('eposta', models.CharField(max_length=30)),
                ('sifre', models.CharField(max_length=15)),
            ],
        ),
    ]
