# Generated by Django 4.2.3 on 2023-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_iletisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=50)),
                ('yorum', models.CharField(max_length=3000)),
            ],
        ),
    ]
