# Generated by Django 4.2.3 on 2023-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='rol',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
