# Generated by Django 4.2.3 on 2023-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_kullanici_isi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='hak',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
